#!/bin/bash

# Railway Environment Variables Setup Script
# ==========================================
# This script shows you the EXACT environment variables needed for Railway

echo "🚀 Railway Environment Variables Required"
echo "=========================================="
echo ""
echo "Go to your Railway project dashboard:"
echo "1. Click on your deployment"
echo "2. Go to 'Variables' tab"
echo "3. Add these variables:"
echo ""
echo "Required Variables:"
echo "-------------------"
echo "OPENAI_API_KEY=<your-openrouter-api-key>"
echo "  OR"
echo "GROQ_API_KEY=<your-groq-api-key>"
echo ""
echo "Recommended Variables:"
echo "----------------------"
echo "DEBUG=False"
echo "SECRET_KEY=<generate-a-strong-random-key>"
echo "OPENAI_TIMEOUT=600"
echo "ALLOWED_HOSTS=unthinkable-meeting-summarizer-production.up.railway.app,*.up.railway.app"
echo ""
echo "Optional Variables:"
echo "-------------------"
echo "OPENAI_BASE_URL=https://openrouter.ai/api/v1"
echo "OPENAI_GPT_MODEL=meta-llama/llama-3.1-8b-instruct"
echo "GROQ_WHISPER_MODEL=whisper-large-v3"
echo ""
echo "=========================================="
echo ""
echo "📝 How to get FREE API keys:"
echo ""
echo "1. Groq API (FREE Whisper transcription):"
echo "   https://console.groq.com/keys"
echo ""
echo "2. OpenRouter API (for summarization):"
echo "   https://openrouter.ai/keys"
echo ""
echo "=========================================="
echo ""
echo "⚠️  IMPORTANT:"
echo "After adding variables, Railway will automatically redeploy."
echo "Wait 1-2 minutes for the deployment to complete."
echo ""
echo "Then test your upload again!"
echo "=========================================="
