# Generated by Django 5.2.3 on 2025-10-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of what needs to be done', null=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='impact',
            field=models.TextField(blank=True, help_text='Why this task matters and expected outcome', null=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='', help_text='Action item title/summary', max_length=300),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='task',
            field=models.CharField(blank=True, help_text='Task or action item description (legacy field)', max_length=300, null=True),
        ),
    ]
