# Generated by Django 5.2.3 on 2025-10-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_actionitem_description_actionitem_impact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='actionitem',
            name='impact',
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_starred',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this meeting is starred/favorited'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='task',
            field=models.CharField(help_text='Task or action item description', max_length=300),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='title',
            field=models.CharField(default='Untitled Task', help_text='Task title (auto-populated from task description)', max_length=300),
        ),
    ]
