# Generated by Django 5.2.3 on 2025-10-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_remove_actionitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='Whether this meeting is starred/favorited'),
        ),
    ]
