# Generated by Django 5.2.3 on 2025-10-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_is_starred'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name (e.g., "Q4 Planning", "Engineering")', max_length=50, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code (e.g., #007bff)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when tag was created')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='related_meetings',
            field=models.ManyToManyField(blank=True, help_text='Other meetings related to this one', related_name='referenced_by', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this meeting', related_name='meetings', to='meetings.tag'),
        ),
    ]
